language: node_js
node_js:
  - "0.8"
branches:
  only:
    - master
before_script: components/angular-ui-docs/.travis/before_script.sh
after_success: components/angular-ui-docs/.travis/after_success.sh
script: "grunt"
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g bower grunt-cli
  - npm install
  - bower install
