---
language: node_js
node_js:
- '0.8'
branches:
  only:
  - master
before_script: components/angular-ui-docs/.travis/before_script.sh
after_success: components/angular-ui-docs/.travis/after_success.sh
script: grunt
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- npm install -g bower grunt-cli
- npm install
- bower install
env:
  global:
  - REPO="git@github.com:angular-ui/ui-chart.git"
  - secure: o9QXzPKwRnnrU79UfD5kEIXMVGXBZuHtyzOuCthe3J2dXKqtwgIbAhdqFjQqKF34rxKVDVFRycEuxk+8FX+M74fewlmuHO8+QV72WuIKZhLavoSeZHccUjwtTqjjdmfu7Vnp2edvDRhAwf2Blr1bFN501bnsxQ0R4Eyak6i8C+A=
  - secure: fm5BPYwpZnaFzstiKnSmQsE/yG8QliHaS+aHNXRKFjMHjQ86x3lDKdz1cIKelMDUde8QNGWnsro+1qvGvaoOjwCDuNV4DeGRZckJJIP5INFWNAPiawJglWFtr3lnSakpdnpvV1/0q6Yb6o04u2Yh8GwqlQY/53YvM3TeoQ6wJXU=
  - secure: GoRqYNLOIBlAOsRUI441Fb8qTEyIsU0eaSemWZqQ3DfFuC91FbOYlgc+KtRtztXCbNM2ugYm1Imn+fqHKrQ8iGpI9K1dpUoNJqhOYzfVtXdNLUCEtE8Bgd1lqWbq5noK8WP52Ozu+/8qNE/7v8vpvSvpnFMKDwsB3bIgToOJ2oU=
  - secure: BPcSLRv+4L/DiaoBu1V6/Z4awpm+9z3ZYcBO2FjVnKlS8IR0LgobgpKc3LCN3rhlOkafrWm53fzyc7b/YV+vnaV+9M7wWaJ0dAWSkzPDdqdGLATqTIIUE70m+t2qP0HtiXzb3DOlGqvcraMDXUnncC5uMRvuzTPRDfiRyJrh/vw=
  - secure: CXOmY8WmyoXKeNrMhS0HJloC936++HuUqTD4s2pqKLo+Qgu4fwR8z43gj2wpJUMaogQwSl42npDHzFg4horrqbW+Bhw3FvyZDuHwefpE+P6xKVoyK0O+O8nzsZQ00jX9p8CW/Owd39v5byU9bt1D8E85lxwQMrpNadLqIFSocFI=
  - secure: f64qW+R0NTq9Ql5lS1IxuDhJpkTouSulWlAlaSwSgePrzby8X9vfNsnBBHajOMAQris/A7/FLLXbdFTniiwW0ZtFjRKgma7NWYLlEwFdf6Sm8ObM60lYFdeH9Ngn2mCgpOLqTLJ7rX86Ce0B0LbOTxNtLoaszVOo4oEr9vV9gnI=
  - secure: g5M719tTa85YrqK6gW63zYwFW5/OkQeEeSr42aSHIL6t4XyZBo+37Mf2Zt/oUXbe8Lkbm/vYPVbSZSXkqpGhUURkYSFcpeCocEMt/DqXmoIgg6mcsemZhcDsCauJWgV6OvQ0FbFT6K1gDiBzTeCBeOnI1PrG5pfzPeTtlUowApI=
  - secure: ExTB1Gf0wAAReUN2KaA7Ew2rR5oNNW2PPzAZlIWl4Al6iMsZ1Ztfups7foQp1FCaWjVUQRDF1Ib1oze51Wym7G8VCBRbCeYvkr5WsFlsl/WV0TTFPTE/vFc0GA4k3FpZX2qXymmHam9kTa5iUi8uHllswJqOhAHzWkwtPWn8GP0=
  - secure: IscKbRmbd99L8mCe7Un8Sky25zitd5cXhOLB+NmlZtWuT/AdBitvexupB3tDBiwFYziTKdFWhoyrDcBFEqlMX/8NSVzEz8+cpePORfiEKfhcBm3s+FQYHMvJJPcnvrDjHXF0QEglutOV5t9NtqhJ8af/LTzXLo3xJHl06i/OKvk=
  - secure: abjduEqSFgM/ZDkyr7chi5yWaiEfmWX9WJczIq28KFqYFzk9LGX2PuzAVWwxZDnuDYqrq0+M/ZQk4a2lGYsScfL1MQZKtMqkvCOwJ6MT0Mdk8YQQZ7gggPGrJvLMzfT79RQomZWsNmGhjEoFQdZ1QYuxj9s0N2b46VvhPdYKXIA=
  - secure: EPN5YrZMDZ/SJOm9UhiJ5Z95pBlyNHyeLNo3k5im1ClkoqPmNNWUMIkvvjggrwAOnKBpcVG0qystpRziaAwNE+IPPM5He+TZ8GqWhSwv5xQIql8Sijh7SzWPEjc3HViwmO6AfrHoOAOnqcLSMtz2707AFNjHV7xNO7ecUsmamU8=
  - secure: JjBZWc5qiUUSgGZWmH/09o8mBfkZsnIYvJ+EDAYcU6A8h0wXrKYEGhvp6fPrilQAqfmKYGBA2oOsMeRy40Fq2RnSF8ynee6rsyS0jez+P3PKHG7it38JVRMnHPFflV7KiNwya9xfFvSACpyOFiEht9T++BScmlxF38Cdar+2du4=
  - secure: WuXGz+RDmn6VAshIMevVVPJZaylU8/X6vhTh302JN4VTkFzD1um13F3obZPPj5K5YLAvHDBB683BVCFM7wyHnRUxGfPqoHXzWsP5s/ylz0E49G6S5k2hP/Mk8BRqB3JbHV+GnvzsOLKq1b2DSXN5Bo7ICwaVxXMrIaJojqyBGwQ=
  - secure: lujuEVEWxfE6e819sLTEpsU/hTgzGy++QjLw7mt38g0iKfjF+3N8DDCC0UirWl3YblBqkr/lXGVDZlUp4K29FRVmp/wFTUx67esSYDGrksUPalzaeMZxVtMhYotCiVzfGcTT3+HX0lUgHkx7rmZZtHQrM/qUtRDFCjnv6lopWGw=
  - secure: L635CLYp+fCTqgRPKzBVC8ANZ5lz0ZdNhG4zO71gkBsIdwdnosZ3xhSrws0io9hmNVEvb255cx10Pe008cKXs3REdgW2MqP/YDDq1eqis7OR+ODyivEmQ54j42/AACMszZQzV+nOQU7CK7gmkWOz+yY+THTWXnDBuwh0cipSshE=
  - secure: TW4uE2GL5zzssWBzCxPwniE6lrPlTsg+zMzUglnivDVP+sYxbCRmbKa51Ah3Fvw0K0vqPf32e3T+TCp8UgSmUurJkwa/S7n2GMjzA266jLd1PejxQcLQ1jG7ihI8H51670jZslCwn1IQL4cUL6KMKsQ1Qujb946CmRHo8ydnqrM=
  - secure: CBsp18XgKD2iZXC8EPFujVt8tUgXCkc+Ao/f0WwVnBRfaSnKji+IpJ+XXPDqTFKEbQZxKvC/A08dphIkqJrThvLYTMEMCTlW22XgVfRqtPrEZnvw+VNMdJ7Ap7xRbYbpWLs26yiOqJmD44RdZ3akRRFLtSPi5UwzW+rALU4l2Bo=
  - secure: Df24eZDX4oho7pIeykjUgHnZoRGdiNIJzLaYfhdnMjD+w0TxN2R7yAY99+zq1qm0g/mEfUvj79HCarApT7DkHBvbd3y7DLfk53h7T8AHNweunzfAGGT5QUN02J4MaeoEK9vZj1feTPsx2RLPYajqB54yaBWN8ywCdOq4utvOv08=
  - secure: fps0gErIc/jPPtex8sWUAdXD5CgHsY7Jq4ej0vGZ33CE6Rraa6lCJ5wjNUQGFY/lwbpqtUuSFMe/gmX0wnVrLNuzIyHF/ViltVfoasfij8N81Dta35wQ6qzUJQt+u6LGgmr+QsEEY0AxY4gwzIv6ZCyL0S3y97EEHdx+L9R6mtM=
  - secure: q9w3uvKlcL09VVqsuqtU92YDzPQwjF6BnzkyjjxbIyDQPlbHAQQF/RAhK5BI2MI7207OnsHplv36266b6F9BFxpu+cUv9NYdmfMS6+Y2JZwfcbtAgT+OjOzyiJjrYIPQCgDb7jYlQGdX3Y1u49SC9f41DsoOw0g/Ose0GJfd5ps=
  - secure: WESxTilvvoQzpNwIFjEQ3ZeUxn/Y3MSlf/qbIFy0isUVVdht1+DNMNNvXBfjF2fCeyZDPjezFG69EBDR3r4dfJJ6kK92DVTcgTQvXiwhCfK2wEy7ki8nn7dzHqjNur0t48qL6HSTjDf37WGQzZf/i28rzehiV8JT5++nvaHfU/o=
  - secure: gRYaP1Hr3lehXi0GdOkgCZPxNFm36X/UtuOg5Qzups3j1wYvV/VagS/id8iULzvXRFko8rtPQ00op2xowNW7lsb8PFXAMohe/IJ3CKY8meIvP7v04gmlaCoqH7jATquH15Hbbfl8mJ1vibXh1Ij1gRaJC6vzaucfWFJFjLPsfQ4=
  - secure: SZTZ+MtOJVSv26hBN0aiuQVGiMDmd6MzMo2je2Gv0ZVQH00b0Qef1ie03eUkUU0LXyYR+D/IRnvy7s0h9OVZOhfbLdyWoxvf0CQFHBTXU/0muZ3HqrJ01DyC6v2XfaoRICw45pHW9b0VgHgZU4iAH8qUhV4WZ2Rzm7+625KA618=
